include:
  - "**/*.rb"
exclude:
  - spec/**/*
  - test/**/*
require: []
domains: []
reporters:
  - rubocop
  - require_not_found
plugins:
  - actioncable
  - actionmailer
  - actionpack
  - actionview
  - activejob
  - activemodel
  - activerecord
  - activestorage
  - activesupport
require_paths: []
